# Generated by Django 3.0.8 on 2021-03-07 21:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=250)),
                ('specialities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('available_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('available_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('apartement_suite_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('breed', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetScheduler.User')),
            ],
        ),
    ]
