# Generated by Django 3.0.8 on 2021-03-07 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetScheduler', '0003_auto_20210307_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='specialities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
