# Generated by Django 3.0.8 on 2021-03-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetScheduler', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
