# Generated by Django 3.0.8 on 2021-03-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetScheduler', '0006_clinic_clinic_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='password',
            field=models.CharField(default='password', max_length=250),
        ),
    ]
