# Generated by Django 3.0.8 on 2021-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetScheduler', '0007_clinic_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(default='Toronto', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='postal_code',
            field=models.CharField(default='H0H0H0', max_length=7),
        ),
    ]
